[HELP]
; RM_RER.INI -- RM-specific parameter file for the third-party RER hand printed
; text recognition module.
; Its knowledge base file (also known as the primary classifier file) to be used
; during the recognition is specified under the [ReR Parameters] section.
; The recognition module can be fine-tuned through the settings located under the
; section [ReParm].
; The value of these settings are the factory defaults of this RM.
; A description for these settings can be found in the KADMOS 4.0i Manual
; (reRecognition GmbH, Germany).

[ReR Parameters]
REC_file=hand

[ReParm]
prep=304
noise_diameter_percent=0
noise_diameter_pixel=0
noise_width_percent=0
noise_length_percent=0
noise_width_pixel=0
noise_length_pixel=0
;grid0=4 width:min-max height:min-max search_area:(left,top,width,height) subgrid_count:count
;grid1=
; .
; .
; .
typograph=0
line_space=0
base_line=0
char_space_min=0
char_space_max=0
code=10000000
options=20
labels=
alc=0
reject_limit=150
pos=0
context=0
trig_factor=100
trig_maximum=32

reject_level=0
