'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Main
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Capture.Main", GetType(Main).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Black Page.
        '''</summary>
        Friend Shared ReadOnly Property BlackPage() As String
            Get
                Return ResourceManager.GetString("BlackPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cabinet.
        '''</summary>
        Friend Shared ReadOnly Property Cabinet() As String
            Get
                Return ResourceManager.GetString("Cabinet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Page.
        '''</summary>
        Friend Shared ReadOnly Property CurrentPage() As String
            Get
                Return ResourceManager.GetString("CurrentPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ECM - Capture.
        '''</summary>
        Friend Shared ReadOnly Property ECMCapture() As String
            Get
                Return ResourceManager.GetString("ECMCapture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to eZConfig.
        '''</summary>
        Friend Shared ReadOnly Property eZConfig() As String
            Get
                Return ResourceManager.GetString("eZConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EzIndex.
        '''</summary>
        Friend Shared ReadOnly Property EzIndex() As String
            Get
                Return ResourceManager.GetString("EzIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fields.
        '''</summary>
        Friend Shared ReadOnly Property Fields() As String
            Get
                Return ResourceManager.GetString("Fields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Free Hand.
        '''</summary>
        Friend Shared ReadOnly Property FreeHand() As String
            Get
                Return ResourceManager.GetString("FreeHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home.
        '''</summary>
        Friend Shared ReadOnly Property Home() As String
            Get
                Return ResourceManager.GetString("Home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import.
        '''</summary>
        Friend Shared ReadOnly Property Import() As String
            Get
                Return ResourceManager.GetString("Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Zones.
        '''</summary>
        Friend Shared ReadOnly Property LoadZones() As String
            Get
                Return ResourceManager.GetString("LoadZones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lookup Fields.
        '''</summary>
        Friend Shared ReadOnly Property LookupFields() As String
            Get
                Return ResourceManager.GetString("LookupFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Magnify.
        '''</summary>
        Friend Shared ReadOnly Property Magnify() As String
            Get
                Return ResourceManager.GetString("Magnify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge.
        '''</summary>
        Friend Shared ReadOnly Property Merge() As String
            Get
                Return ResourceManager.GetString("Merge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Formats.
        '''</summary>
        Friend Shared ReadOnly Property OtherFormats() As String
            Get
                Return ResourceManager.GetString("OtherFormats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page.
        '''</summary>
        Friend Shared ReadOnly Property Page() As String
            Get
                Return ResourceManager.GetString("Page", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record.
        '''</summary>
        Friend Shared ReadOnly Property Record() As String
            Get
                Return ResourceManager.GetString("Record", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend Shared ReadOnly Property Refresh() As String
            Get
                Return ResourceManager.GetString("Refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rotate Left.
        '''</summary>
        Friend Shared ReadOnly Property RotateLeft() As String
            Get
                Return ResourceManager.GetString("RotateLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rotate Right.
        '''</summary>
        Friend Shared ReadOnly Property RotateRight() As String
            Get
                Return ResourceManager.GetString("RotateRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan.
        '''</summary>
        Friend Shared ReadOnly Property Scan() As String
            Get
                Return ResourceManager.GetString("Scan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select All / UnSelect All.
        '''</summary>
        Friend Shared ReadOnly Property SelectAll() As String
            Get
                Return ResourceManager.GetString("SelectAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single Pages.
        '''</summary>
        Friend Shared ReadOnly Property SinglePages() As String
            Get
                Return ResourceManager.GetString("SinglePages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Template.
        '''</summary>
        Friend Shared ReadOnly Property Template() As String
            Get
                Return ResourceManager.GetString("Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tiff Files.
        '''</summary>
        Friend Shared ReadOnly Property TiffFiles() As String
            Get
                Return ResourceManager.GetString("TiffFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zonal Settings.
        '''</summary>
        Friend Shared ReadOnly Property ZonalSettings() As String
            Get
                Return ResourceManager.GetString("ZonalSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zoom In.
        '''</summary>
        Friend Shared ReadOnly Property ZoomIn() As String
            Get
                Return ResourceManager.GetString("ZoomIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zoom Out.
        '''</summary>
        Friend Shared ReadOnly Property ZoomOut() As String
            Get
                Return ResourceManager.GetString("ZoomOut", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
