'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class eZUserSession
    Public Property SessionId As Integer
    Public Property ECMLoginId As Integer
    Public Property Logged As Nullable(Of Integer)
    Public Property TemplateId As Integer
    Public Property itemid As Integer
    Public Property UplaodDocument As Boolean
    Public Property ViewDocument As Boolean
    Public Property CommentsId As Integer
    Public Property CheckOut As Boolean
    Public Property LinkId As Integer
    Public Property AlertDocument As Boolean
    Public Property CreatedOn As String
    Public Property UpdatedOn As String
    Public Property CreatedBy As Integer
    Public Property UpdatedBy As Integer
    Public Property Isdeleted As Boolean
    Public Property IndexingChange As Boolean
    Public Property Deleted As Nullable(Of Integer)
    Public Property bookmarks As Integer
    Public Property email As Integer
    Public Property checkin As Integer
    Public Property loggedfrom As String
    Public Property loggedat As String
    Public Property PrintDoc As Nullable(Of Boolean)

End Class
