'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class InvitaECMDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=InvitaECMDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property eZECMLogins() As DbSet(Of eZECMLogin)
    Public Overridable Property eZUserSessions() As DbSet(Of eZUserSession)
    Public Overridable Property eZCA_3_9_items() As DbSet(Of eZCA_3_9_items)
    Public Overridable Property eZWorkflowUsers() As DbSet(Of eZWorkflowUser)
    Public Overridable Property eZBatchFiles() As DbSet(Of eZBatchFile)

    Public Overridable Function FindFileName(itemid As String, templateId As String) As ObjectResult(Of String)
        Dim itemidParameter As ObjectParameter = If(itemid IsNot Nothing, New ObjectParameter("Itemid", itemid), New ObjectParameter("Itemid", GetType(String)))

        Dim templateIdParameter As ObjectParameter = If(templateId IsNot Nothing, New ObjectParameter("TemplateId", templateId), New ObjectParameter("TemplateId", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("FindFileName", itemidParameter, templateIdParameter)
    End Function

End Class
