'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class eZCA_3_9_items
    Public Property itemid As Integer
    Public Property ERSId As Integer
    Public Property TemplateId As Integer
    Public Property RIM_Number As String
    Public Property TIN_Number As String
    Public Property RIM_Type As String
    Public Property Document_Type As String
    Public Property RIM_Branch As String
    Public Property RIM_Name As String
    Public Property File_Location As String
    Public Property LAST_KYC_DATE As Nullable(Of Date)
    Public Property Quality_Check As String
    Public Property Account_Number As String
    Public Property ifilepath As String
    Public Property ifilename As String
    Public Property ifiletype As String
    Public Property eZFrom As String
    Public Property version As String
    Public Property dtitle As String
    Public Property dauthor As String
    Public Property dsubject As String
    Public Property dkeywords As String
    Public Property checkout As String
    Public Property checkoutpath As String
    Public Property checkoutby As Integer
    Public Property dstatus As String
    Public Property dsize As String
    Public Property nopages As Nullable(Of Integer)
    Public Property Password As String
    Public Property Passwordby As Nullable(Of Integer)
    Public Property PasswordRemoveby As Nullable(Of Integer)
    Public Property Encrypt As String
    Public Property Encryptby As Nullable(Of Integer)
    Public Property Decryptby As Nullable(Of Integer)
    Public Property CreatedOn As String
    Public Property UpdatedOn As String
    Public Property CreatedBy As Integer
    Public Property UpdatedBy As Integer
    Public Property Isdeleted As Boolean
    Public Property Mandate_Type As String
    Public Property File_Status As String
    Public Property Account_Type As String
    Public Property Account_Status As String

End Class
