'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class eZECMLogin
    Public Property ECMLoginId As Integer
    Public Property IsADUser As Boolean
    Public Property LoginName As String
    Public Property Pasword As String
    Public Property ECMProfileId As Integer
    Public Property CreatedOn As String
    Public Property UpdatedOn As String
    Public Property CreatedBy As Integer
    Public Property UpdatedBy As Integer
    Public Property Isdeleted As Boolean
    Public Property ECMUserTypeId As Integer
    Public Property LanguageId As Integer
    Public Property chart1 As Nullable(Of Integer)
    Public Property chart2 As Nullable(Of Integer)
    Public Property chart3 As Nullable(Of Integer)
    Public Property IsFaxUser As Nullable(Of Boolean)
    Public Property Signatureid As String

End Class
